# Generated by Django 4.2 on 2024-02-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
