# Generated by Django 4.2 on 2024-03-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_contactmessage_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
